### ISSUE TITLE
Run cypress smoke tests as a github action

### ISSUE THREAD

**Issue by aszs** [onecommons/unfurl-gui#19]
We should run cypress smoke tests as a github action to validate commits to unfurl-gui. (Testing against gitlab-oc is more complicated)
 
See https://github.com/cypress-io/github-action and https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/

**Comment by AjBreidenbach** [comment]
The 2019 article even has a comment which describes how they got apollo working in their ci environment!

Thought this may also be useful in case we need more than a few iterations to get it working https://github.com/nektos/act

**Comment by atreyasinha** [comment]
![Screen Shot 2022-02-21 at 9 50 14 AM](https://user-images.githubusercontent.com/84874851/155005500-8a4c5b81-a8a0-478d-bce3-cbfdcb8546a6.png)

**Comment by aszs** [comment]
let's upload the videos and screenshots as artifacts

**Comment by aszs** [comment]
I updated the action to run on any push. Assigning to @AjBreidenbach to choose a subset of tests we want to always run and expect to pass.

**Comment by aszs** [comment]
merged into handover what we have as of now... tests seem to pass... declaring victory and closing....
