### ISSUE TITLE
Replace Project ID with link to "projectname" page

### ISSUE THREAD

**Issue by christinezapata** [onecommons/unfurl-gui#24]
When new users are on an application blueprint page, there will be a link "View Project" underneath the application blueprint title that replaces the project ID # which is what is currently there from Gitlab. 

The link should take the user to the "projectname" page that contains the Project Sidebar Nav (this is the first nav menu item at the top left with the thumbnail image). 

Example: 
https://www.figma.com/file/xPHScUbN6waRNU3LHhn5G5/UI---WIP?node-id=1298%3A41808

"View Project" should link here: https://unfurl.cloud/demo/apostrophe-demo/

**Comment by AjBreidenbach** [comment]
screenshotting for my own reference
![unfurl-mockups-view-project](https://user-images.githubusercontent.com/24526487/154149254-47936d23-8a99-4526-ba8e-c8e323209328.png)

**Comment by AjBreidenbach** [comment]
Merged wtih PR #25
